-- Carga inicial de las 47 tareas (tomadas del Excel organizado de la pestaña WEB)
-- Ejecutar UNA sola vez, después de 01_esquema.sql, en Supabase > SQL Editor
insert into public.tareas (codigo, grupo, categoria, tarea, responsable, lider, prioridad, fecha_limite, estado, proveedor, valor_total, valor_abonado, fecha_proximo_pago, proximo_paso, depende_de, observaciones) values -- Columnas que se llenan
  ('A-01', 'Vestuario y arreglo – Ana', 'Vestido', 'Elegir vestido', 'Ana', 'Ana', 'Alta', '2026-09-30', 'Listo', null, 4000000, 1950000, null, 'Confirmar el valor real abonado (en el original estaba como fórmula 3.900.000 / 2).', null, 'Tener en cuenta confección y ajustes.'), -- A-01
  ('A-02', 'Vestuario y arreglo – Ana', 'Zapatos', 'Elegir zapatos', 'Ana', 'Ana', 'Alta', '2026-09-12', 'No iniciado', null, null, null, null, null, null, 'Reprogramada desde 30/09 para no chocar con otras tareas.'), -- A-02
  ('A-03', 'Vestuario y arreglo – Ana', 'Accesorios', 'Elegir accesorios', 'Ana', 'Ana', 'Alta', '2026-09-19', 'No iniciado', null, null, null, null, null, null, 'Reprogramada desde 30/09 para no chocar con otras tareas.'), -- A-03
  ('A-04', 'Vestuario y arreglo – Ana', 'Vestido', 'Prueba del vestido', 'Ana', 'Ana', 'Alta', '2026-09-26', 'No iniciado', null, null, null, null, null, 'A-02', 'La prueba se debe hacer con los zapatos que se usarán en la boda. Reprogramada desde 30/09 para no chocar con otras tareas.'), -- A-04
  ('A-05', 'Vestuario y arreglo – Ana', 'Maquillaje', 'Elegir maquilladora', 'Ana', 'Ana', 'Media', '2026-10-15', 'Listo', 'Cata Lopez Beauty', 1400000, 700000, null, 'Cuadrar fecha de la prueba de maquillaje.', null, null), -- A-05
  ('A-06', 'Vestuario y arreglo – Ana', 'Peinado', 'Elegir peinadora', 'Ana', 'Ana', 'Media', '2026-10-15', 'No iniciado', null, null, null, null, null, null, null), -- A-06
  ('A-07', 'Vestuario y arreglo – Ana', 'Vestido', 'Última prueba del vestido', 'Ana', 'Ana', 'Alta', '2027-01-20', 'No iniciado', null, null, null, null, null, 'A-04', null), -- A-07
  ('B-01', 'Vestuario y arreglo – Juan', 'Traje', 'Elegir traje de Juan', 'Juan', 'Juan', 'Alta', '2026-09-15', 'No iniciado', null, null, null, null, null, null, 'Reprogramada desde 30/09 para no chocar con otras tareas.'), -- B-01
  ('B-02', 'Vestuario y arreglo – Juan', 'Zapatos', 'Elegir zapatos de Juan', 'Juan', 'Juan', 'Media', '2026-11-15', 'No iniciado', null, null, null, null, null, 'B-01', 'Tarea nueva (antes sugerida). Fecha tentativa: ajustar.'), -- B-02
  ('B-03', 'Vestuario y arreglo – Juan', 'Accesorios', 'Elegir accesorios de Juan (corbata o corbatín, gemelos, cinturón)', 'Juan', 'Juan', 'Media', '2026-11-30', 'No iniciado', null, null, null, null, null, 'B-01', 'Tarea nueva (antes sugerida). Fecha tentativa: ajustar.'), -- B-03
  ('B-04', 'Vestuario y arreglo – Juan', 'Arreglo personal', 'Agendar corte de cabello y barba', 'Juan', 'Juan', 'Baja', '2027-01-23', 'No iniciado', null, null, null, null, null, null, 'Tarea nueva (antes sugerida). Fecha tentativa: ajustar. Idealmente una semana antes de la boda.'), -- B-04
  ('C-01', 'Ceremonia religiosa y trámites', 'Iglesia', 'Confirmar documentos y requisitos de la iglesia', 'Ambos', null, 'Alta', '2026-09-15', 'No iniciado', null, null, null, null, null, null, null), -- C-01
  ('C-02', 'Ceremonia religiosa y trámites', 'Iglesia', 'Ir a la iglesia a tramitar documentos', 'Ambos', null, 'Alta', '2026-09-15', 'No iniciado', null, null, null, null, null, 'C-01', null), -- C-02
  ('C-03', 'Ceremonia religiosa y trámites', 'Iglesia', 'Hacer curso prematrimonial', 'Ambos', null, 'Alta', '2026-09-15', 'No iniciado', null, null, null, null, null, null, null), -- C-03
  ('C-04', 'Ceremonia religiosa y trámites', 'Argollas', 'Comprar argollas', 'Ambos', null, 'Media', '2026-10-31', 'No iniciado', null, null, null, null, null, null, null), -- C-04
  ('C-05', 'Ceremonia religiosa y trámites', 'Documentos', 'Revisar documentos del matrimonio', 'Ambos', null, 'Alta', '2027-01-20', 'No iniciado', null, null, null, null, null, 'C-02, C-03', null), -- C-05
  ('C-06', 'Ceremonia religiosa y trámites', 'Iglesia', 'Confirmar reserva de iglesia, sacerdote y hora de la ceremonia', 'Ambos', null, 'Alta', '2026-10-15', 'No iniciado', null, null, null, null, null, 'C-01', 'Tarea nueva (antes sugerida). Fecha tentativa: ajustar.'), -- C-06
  ('C-07', 'Ceremonia religiosa y trámites', 'Cortejo', 'Definir padrinos y cortejo', 'Ambos', null, 'Media', '2026-10-31', 'No iniciado', null, null, null, null, null, null, 'Tarea nueva (antes sugerida). Fecha tentativa: ajustar. Suele requerirse para los documentos de la iglesia.'), -- C-07
  ('C-08', 'Ceremonia religiosa y trámites', 'Documentos', 'Confirmar el registro civil del matrimonio religioso', 'Ambos', null, 'Media', '2027-02-27', 'No iniciado', null, null, null, null, null, 'C-05', 'Tarea nueva (antes sugerida). Fecha tentativa: ajustar. Paso posterior a la ceremonia.'), -- C-08
  ('D-01', 'Lugar y organización', 'Hacienda y wedding planner', 'Seguimiento al contrato y pagos (Hacienda / wedding planner)', 'Ambos', null, 'Alta', null, 'En proceso', 'Hacienda La Victoria', 32636217, 7225000, null, 'Confirmar fechas de pago del saldo de $25.411.217.', null, 'Contrato firmado en jun/jul-2026 (ver carpeta ''La Victoria''). Validar si Hacienda y wedding planner son el mismo proveedor o van en filas separadas. Fecha límite ''Por confirmar'' en el original.'), -- D-01
  ('E-01', 'Fotografía, video y entretenimiento', 'Fotografía', 'Cotizar y contratar fotógrafo', 'Ambos', null, 'Alta', '2026-09-12', 'No iniciado', null, null, null, null, null, 'I-01', 'Reprogramada desde 30/09 para no chocar con otras tareas.'), -- E-01
  ('E-02', 'Fotografía, video y entretenimiento', 'Video', 'Cotizar y contratar video', 'Ambos', null, 'Alta', '2026-09-15', 'No iniciado', null, null, null, null, null, 'I-01', 'Reprogramada desde 30/09 para no chocar con otras tareas.'), -- E-02
  ('E-03', 'Fotografía, video y entretenimiento', 'Show', 'Cotizar y dar anticipo – caricaturas', 'Ambos', null, 'Alta', '2026-09-20', 'No iniciado', null, null, null, null, null, 'I-01', 'En el original solo decía ''Cotizar y realizar anticipo''; se identificó como caricaturas (confirmar). Reprogramada desde 30/09 para no chocar con otras tareas.'), -- E-03
  ('E-04', 'Fotografía, video y entretenimiento', 'Show', 'Cotizar y dar anticipo – hora loca', 'Ambos', null, 'Alta', '2026-09-26', 'No iniciado', null, null, null, null, null, 'I-01', 'En el original solo decía ''Cotizar y realizar anticipo''; se identificó como hora loca (confirmar). Reprogramada desde 30/09 para no chocar con otras tareas.'), -- E-04
  ('E-05', 'Fotografía, video y entretenimiento', 'Música', 'Contratar música para ceremonia y cóctel', 'Ana', 'Ana', 'Alta', '2026-09-30', 'Listo', 'Cantante Lena Violín', 1450000, 435000, null, null, null, 'Violín y piano para la iglesia; solo violín en el cóctel.'), -- E-05
  ('E-06', 'Fotografía, video y entretenimiento', 'Música', 'Crear lista de canciones', 'Ambos', null, 'Baja', '2026-12-15', 'No iniciado', null, null, null, null, null, 'E-05', null), -- E-06
  ('F-01', 'Recepción y ambientación', 'Decoración', 'Definir concepto y decoración', 'Ambos', null, 'Alta', '2026-10-15', 'No iniciado', null, null, null, null, null, null, null), -- F-01
  ('F-02', 'Recepción y ambientación', 'Comida', 'Definir menú y hacer degustación', 'Ambos', null, 'Media', '2026-10-30', 'No iniciado', null, null, null, null, 'Revisar qué incluye la Hacienda.', 'D-01', null), -- F-02
  ('F-03', 'Recepción y ambientación', 'Comida', 'Elegir torta', 'Ambos', null, 'Media', '2026-11-15', 'No iniciado', null, null, null, null, null, null, null), -- F-03
  ('F-04', 'Recepción y ambientación', 'Recuerdos', 'Elegir detalles para invitados', 'Ana', 'Ana', 'Baja', '2026-11-30', 'No iniciado', null, null, null, null, null, null, null), -- F-04
  ('F-05', 'Recepción y ambientación', 'Decoración', 'Definir números de mesa y señalización', 'Ana', 'Ana', 'Baja', '2026-12-15', 'No iniciado', null, null, null, null, null, 'F-01, G-05', null), -- F-05
  ('F-06', 'Recepción y ambientación', 'Flores', 'Definir ramo y flores', 'Ana', 'Ana', 'Media', '2026-12-15', 'No iniciado', null, null, null, null, 'Verificar si ya está incluido en la decoración.', 'F-01', 'Tarea nueva (antes sugerida). Fecha tentativa: ajustar.'), -- F-06
  ('F-07', 'Recepción y ambientación', 'Momentos', 'Preparar primer baile', 'Ambos', null, 'Baja', '2027-01-15', 'No iniciado', null, null, null, null, null, 'E-06', 'Tarea nueva (antes sugerida). Fecha tentativa: ajustar.'), -- F-07
  ('G-01', 'Invitados y comunicación', 'Lista de invitados', 'Definir lista definitiva de invitados', 'Ambos', null, 'Alta', '2026-09-15', 'No iniciado', null, null, null, null, 'Separar invitados de cada familia.', null, 'Reconciliar con la capacidad contratada en la Hacienda (documentos mencionan 70 y 80 pax).'), -- G-01
  ('G-02', 'Invitados y comunicación', 'Invitación', 'Enviar save the date', 'Ambos', null, 'Media', '2026-10-15', 'Listo', null, null, null, null, null, null, 'Publicado en GitHub Pages.'), -- G-02
  ('G-03', 'Invitados y comunicación', 'Invitación', 'Diseñar invitaciones', 'Ambos', null, 'Media', '2026-10-15', 'En proceso', null, null, null, null, 'Agregar link de RSVP y mapa de Google; confirmar dress code y horario.', null, 'Cubo 3D ya construido.'), -- G-03
  ('G-04', 'Invitados y comunicación', 'Invitación', 'Enviar invitaciones', 'Ambos', null, 'Media', '2026-11-01', 'No iniciado', null, null, null, null, null, 'G-01, G-03, G-06', null), -- G-04
  ('G-05', 'Invitados y comunicación', 'Lista de invitados', 'Confirmar número final de invitados', 'Ambos', null, 'Alta', '2026-12-15', 'No iniciado', null, null, null, null, null, 'G-04', null), -- G-05
  ('G-06', 'Invitados y comunicación', 'Regalos', 'Definir lista de regalos o lluvia de sobres', 'Ambos', null, 'Media', '2026-10-25', 'No iniciado', null, null, null, null, null, null, 'Tarea nueva (antes sugerida). Fecha tentativa: ajustar. Conviene incluirlo en la invitación.'), -- G-06
  ('H-01', 'Logística del día', 'Agenda del día', 'Crear cronograma del día', 'Ambos', null, 'Alta', '2026-11-15', 'No iniciado', null, null, null, null, 'Iniciar primer borrador.', null, 'Lugar y hora (3:00 p. m.) ya confirmados.'), -- H-01
  ('H-02', 'Logística del día', 'Transporte', 'Definir transporte', 'Juan', 'Juan', 'Media', '2026-11-15', 'No iniciado', null, null, null, null, null, null, null), -- H-02
  ('H-03', 'Logística del día', 'Alojamiento', 'Reservar alojamiento para la noche de bodas', 'Ambos', null, 'Media', '2026-11-30', 'No iniciado', null, null, null, null, null, null, 'Tarea nueva (antes sugerida). Fecha tentativa: ajustar. El viaje empieza el 31 de enero.'), -- H-03
  ('I-01', 'Presupuesto y cierre', 'Presupuesto', 'Armar presupuesto total', 'Ambos', null, 'Alta', '2026-09-10', 'No iniciado', null, null, null, null, 'Definir presupuesto máximo.', null, null), -- I-01
  ('I-02', 'Presupuesto y cierre', 'Cierre', 'Confirmar todos los proveedores', 'Juan', 'Juan', 'Alta', '2027-01-15', 'No iniciado', null, null, null, null, null, null, null), -- I-02
  ('I-03', 'Presupuesto y cierre', 'Cierre', 'Revisar y programar pagos finales', 'Ambos', null, 'Alta', '2027-01-15', 'No iniciado', null, null, null, null, null, null, null), -- I-03
  ('J-01', 'Luna de miel', 'Viaje', 'Reservar y pagar luna de miel', 'Ambos', null, 'Alta', '2026-11-30', 'No iniciado', null, null, null, null, 'Elegir destino (San Andrés, Cancún, Punta Cana o Aruba).', null, 'Viaje planeado del 31-ene al 4-feb-2027; comparativo de precios ya hecho.'), -- J-01
  ('J-02', 'Luna de miel', 'Documentos de viaje', 'Revisar pasaportes y requisitos del destino', 'Ambos', null, 'Media', '2026-12-15', 'No iniciado', null, null, null, null, null, 'J-01', 'Tarea nueva (antes sugerida). Fecha tentativa: ajustar.') -- J-02
on conflict (codigo) do nothing; -- Si la tarea ya existe, no la duplica
